// leave off @2x/@3x
const images = {
    // icon: require('../../assets/icon.png'),
    image_bitmap: require('../../assets/images/bitmap.png'),
    icon_menu: require('../../assets/icons/menu.png'),
    icon_phone_header: require('../../assets/icons/phone.png'),
    icon_viet_nam: require('../../assets/icons/icon_vietnam.png'),
    icon_english: require('../../assets/icons/icon_english.png'),
    icon_person: require('../../assets/icons/person.png'),
    icon_avatar: require('../../assets/icons/icon_avatar.png'),
    icon_faceid: require('../../assets/icons/icon_faceid.png'),
    icon_fingerprint: require('../../assets/icons/fingerprint.png'),
    icon_load: require('../../assets/icons/load.gif'),
    icon_logout: require('../../assets/icons/logout.png'),
    background: require('../../assets/images/background.png'),
    logo_365_boss_white: require('../../assets/images/logo_365_boss_white.png'),
    logo_365: require('../../assets/images/pos365.jpg'),
    icon_shop: require('../../assets/icons/icon_shop.png'),
    icon_password: require('../../assets/icons/icon_password.png'),
    icon_user_name: require('../../assets/icons/icon_user_name.png'),
    icon_calendar: require('../../assets/icons/icon_calendar.png'),
    icon_placeholder: require('../../assets/icons/icon_placeholder.png'),
    icon_arrow_down: require('../../assets/icons/icon_arrow_down.png'),
    icon_filter: require('../../assets/icons/icon_filter.png'),
    icon_undo: require('../../assets/icons/undo.png'),
    icon_redo: require('../../assets/icons/redo.png'),
    icon_room_off: require('../../assets/icons/icon_table_unselected.png'),
    icon_room_on: require('../../assets/icons/icon_table_selected.png'),
    icon_up: require('../../assets/icons/up.png'),
    icon_checked: require('../../assets/icons/download.png'),
    arrow_down: require('../../assets/icons/down-arrow.png'),
    icon_bell_gray: require('../../assets/icons/icon_bell_gray.png'),
    icon_bell_blue: require('../../assets/icons/icon_bell_blue.png'),
    icon_bell: require('../../assets/icons/bell.png'),
    icon_red_x: require('../../assets/icons/icon_red_x.png'),

    icon_home: require('../../assets/icons/icon_home.png'),
    icon_home_active: require('../../assets/icons/home_active.png'),
    icon_invoice: require('../../assets/icons/icon_invoice.png'),
    icon_transfer_money: require('../../assets/icons/icon_transfer_money.png'),
    icon_table: require('../../assets/icons/icon_table.png'),
    icon_more: require('../../assets/icons/icon_more.png'),
    icon_more_active: require('../../assets/icons/icon_more_active.png'),
    icon_line_chart: require('../../assets/icons/icon_line_chart.png'),

    icon_truck: require('../../assets/icons/icon_truck.png'),
    icon_menu_2: require('../../assets/icons/icon_menu.png'),
    icon_star: require('../../assets/icons/icon_star.png'),
    icon_setting: require('../../assets/icons/icon_setting.png'),
    icon_setting_2: require('../../assets/icons/icon_setting(2).png'),
    icon_report: require('../../assets/icons/icon_report.png'),
    icon_phone: require('../../assets/icons/icon_phone.png'),
    icon_message: require('../../assets/icons/icon_message.png'),
    icon_send: require('../../assets/icons/icon_send.png'),
    icon_waiting: require('../../assets/icons/icon_waiting_4.png'),
    icon_inventory: require('../../assets/icons/inventory.png'),
    icon_exchange: require('../../assets/icons/exchange.png'),
    icon_history: require('../../assets/icons/time.png'),
    icon_notification: require('../../assets/icons/notification.png'),
    icon_product: require('../../assets/icons/icon_product.png'),
    icon_placeholder_white: require("../../assets/icons/icon_placeholder_white.png"),
    icon_customer: require("../../assets/icons/icon_customer.png"),
    icon_phone_2: require("../../assets/icons/icon_phone-2.png"),
    icon_dolar: require("../../assets/icons/icon_dolar.png"),
    icon_debt: require("../../assets/icons/icon_debt.png"),
    icon_woman: require("../../assets/icons/icon_woman.png"),
    icon_male: require("../../assets/icons/icon_male.png"),
    icon_group: require("../../assets/icons/icon_group.png"),
    default_food_image: require('../../assets/images/default-image.png'),
    icon_return: require("../../assets/icons/return.png")

}

export default images
