export const Constant = {
    HOTLINE: "1900 4515",
    PORTRAIT: "PORTRAIT",
    LANDSCAPE: "LANDSCAPE",
    TABLET: "TABLET",
    PHONE: "PHONE",
    CURRENT_ACCOUNT: "CURRENT_ACCOUNT",
    LOAD_LIMIT: 20,
    VENDOR_SESSION: "VENDOR_SESSION",
    IPPRINT: "IPPRINT"
};